Sprint3
asyatestp/Sprint_3 pull request #1
Opened 2023-07-11 18:50 UTC by asyatestp

2023-07-13 20:59 UTC, kadirovgm requested changes

2023-07-13 20:59 UTC, kadirovgm commented on .gitignore
> +# Covers JetBrains IDEs: IntelliJ, RubyMine, PhpStorm, AppCode, PyCharm, CLion, Android Studio, WebStorm and Rider
Можно лучше: в файле гитигнора лучше оставлять только те локальные файлы, что не должны быть запушены в общий репозиторий, в твоем случае ты использовала общий шаблон, это не совсем верно, мы должны избегать использования ненужного кода в проекте.

2023-07-13 20:59 UTC, kadirovgm commented on README.md
> +
отлично! хорошее readme
здесь стоит добавить описание проекта, использованные библиотеки и зависимости, описание тестов 

желательно все описывать в markdown

2023-07-13 20:59 UTC, kadirovgm commented on conftest.py
> +def driver():
отлично!

2023-07-13 20:59 UTC, kadirovgm commented on data.py
> +class Data:
отлично! молодец, что вынес тестовые данные в отдельный файл

тестовые статичные данные лучше выносить в отдельный файл типа [data.py](http://data.py/) или [urls.py](http://urls.py/)
Это нужно для легкой поддержке проекта и переиспользовании тестовых данных, мы должны стремиться к тому, чтобы разделять код и тестовые данные, тем самым избегая повторений.

2023-07-13 20:59 UTC, kadirovgm commented on locators.py
> +class Locators:
- Можно лучше: класс с локаторами лучше разделить на несколько: например `AuthPageLocators`, `MainPageLocators`
Сейчас это не критично, но в будущем это точно стоит сделать, так как таким образом ты не будешь импортить лишние локаторы в файл с тестами на экран авторизации. Т.е. у каждой страницы должен быть свой класс с локаторами.
    
    При таком подходе код станет лаконичнее, легко поддерживаемой. Ведь у экрана авторизации и у экрана главной могут быть свои NEXT_BUTTON например. Тогда можно будет легко оба обозвать именно так:
    `MainPageLocators.NEXT_BUTTON` и `AuthPageLocators.NEXT_BUTTON`
    
    
Сейчас этого не требую, просто как информация

2023-07-13 20:59 UTC, kadirovgm commented on locators.py
> +    SAVE_BUTTON = (By.XPATH, ".//button[text()='Сохранить']")  # Кнопка "Сохранить"
локаторы хорошие!

2023-07-13 20:59 UTC, kadirovgm commented on urls.py
> +class Urls:
отлично!

2023-07-13 20:59 UTC, kadirovgm commented on tests/test_authorization.py
> +    ''' Проверка авторизации по кнопке "Войти в аккаунт" на главной '''
лайк, за докстринг!

2023-07-13 20:59 UTC, kadirovgm commented on tests/test_authorization.py
> +    driver.quit()
нужно исправить: у тебя ведь уже в фикстуре driver используется teardown метод driver.quit(), так что эта строчка в конце всех тестов лишняя

2023-07-13 20:59 UTC, kadirovgm commented on tests/test_authorization.py
> +    WebDriverWait(driver, 10).until(EC.element_to_be_clickable(Locators.INTO_ACCOUNT_BUTTON))
можно лучше: нам стоит избегать в будущем всякого повторения кода, поэтому можно было строки авторизации и регистрации вынести, например, в файл helpers.py, как функции и переиспользовать в тестах, иначе получается что одни и те же шаги прописываем несколько раз

2023-07-13 20:59 UTC, kadirovgm commented on tests/test_lk.py
> +    assert driver.current_url == 'https://stellarburgers.nomoreparties.site/'
можно лучше: почему не вынесла URL в файл url.py ?

2023-07-13 20:59 UTC, kadirovgm commented on tests/test_lk.py
> +    assert driver.current_url == 'https://stellarburgers.nomoreparties.site/account/profile'
нужно исправить: проверка того, что URL поменялся на <url> не гарантирует, что страница прогрузилась, поэтому стоит ориентироваться на какие-либо элементы страницы, чекать, что они появились и отображаются корректно

2023-07-13 20:59 UTC, kadirovgm commented on tests/test_registration.py
> +    WebDriverWait(driver, 10).until(EC.element_to_be_clickable(Locators.INTO_ACCOUNT_BUTTON))
можно лучше: с шагами регистрации та же история, стоит вынести как отдельную функцию и переиспользовать во всех тестах, где нужно регаться, иначе это противоречит основным принципам программирования, если мы одинаковый код повторяем во всех тестах

сейчас не требую исправить, скорее готовлю к тому, то будет в 4 спринте :)

2023-07-17 15:37 UTC, asyatestp commented on tests/test_lk.py
> +    assert driver.current_url == 'https://stellarburgers.nomoreparties.site/account/profile'
Исправила

2023-07-17 15:37 UTC, asyatestp commented on tests/test_authorization.py
> +    driver.quit()
Исправила

2023-07-18 10:34 UTC, kadirovgm approved these changes

2023-07-19 08:21 UTC, merged